'use client';

import { motion } from 'framer-motion';
import {
  AlertTriangle,
  TrendingUp,
  Shield,
  Percent,
  Wallet,
  PieChart,
  Activity,
  CheckCircle,
  XCircle,
  Lightbulb,
} from 'lucide-react';

const sections = [
  {
    icon: TrendingUp,
    title: 'The Nature of DSJEX',
    number: '1',
    content: [
      'DSJEX is a quantitative trading platform.',
      'Members pool capital into a shared fund.',
      'AI systems and algorithms use this capital to open and close trades in real markets: gold, forex, crypto, indices, etc.',
    ],
    highlight: 'There is no "money from person A paying person B." Investor returns come from the actual trading profits generated by the fund.',
  },
  {
    icon: Shield,
    title: 'Only 1% Capital Used for Trading',
    number: '2',
    content: [
      'DSJ uses only 1% of investor capital to trade BTC/USDT.',
      'BG cooperates with futures trading on BTC/USDT because of its high liquidity and strong profit potential.',
    ],
    bullets: [
      'Risk is tightly controlled',
      'The main fund remains protected',
    ],
  },
  {
    icon: Percent,
    title: 'About the "99.6%" Figure',
    number: '3',
    content: [
      'This number refers to the AI\'s prediction accuracy when generating trading signals.',
      'It does NOT mean every trade is profitable.',
    ],
    warning: 'Profit or loss depends on trade size. One small winning trade + one large losing trade can still result in a loss.',
    note: 'The 99.6% figure usually comes from backtesting, not a guarantee of continuous real-market performance.',
  },
  {
    icon: Wallet,
    title: 'Where Does Investor Payout Come From?',
    number: '4',
    content: [
      'Funds paid to investors come from the actual net profit of the trading fund after AI trades are completed.',
    ],
    distribution: [
      { label: 'Investors', percent: '60-65%', color: 'text-green-400' },
      { label: 'BG (Partner/Operator)', percent: '30%', color: 'text-blue-400' },
      { label: 'DSJEX (Operations & Technology)', percent: '5-10%', color: 'text-purple-400' },
    ],
  },
  {
    icon: PieChart,
    title: 'Example Illustration',
    number: '5',
    example: {
      fund: '$1,000,000',
      profit: '$50,000',
      splits: [
        { label: 'Investors receive 60%', amount: '$30,000' },
        { label: 'BG receives 30%', amount: '$15,000' },
        { label: 'DSJEX receives 10%', amount: '$5,000' },
      ],
    },
    warning: 'If the fund loses money, there is nothing to distribute. Everyone shares the loss according to capital and agreement.',
  },
  {
    icon: Activity,
    title: 'Profits Are NOT Always Stable',
    number: '6',
    formulas: [
      'Win rate ≠ total profit',
      'Profit = (wins × average gain) − (losses × average loss)',
    ],
    riskManagement: [
      'Quick stop-losses',
      'Position control',
      'Reduced leverage during high volatility',
    ],
    note: 'The 99.6% figure reflects prediction accuracy under specific conditions, not a guaranteed profit.',
  },
];

export default function DSJEXExplainer() {
  return (
    <section id="dsjex-explained" className="py-20 bg-navy relative overflow-hidden">
      {/* Background pattern */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-gold rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-gold rounded-full blur-3xl" />
      </div>

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-red-500/10 border border-red-500/30 mb-6">
            <AlertTriangle className="w-5 h-5 text-red-400" />
            <span className="text-red-400 font-medium">Important Clarification</span>
          </div>

          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            DSJEX is <span className="text-red-400">NOT</span> a Gambling Platform!
          </h2>
          <p className="text-lg text-white/70 max-w-3xl mx-auto">
            Many people mistakenly confuse DSJEX with gambling or Ponzi models.
            Here&apos;s the reality of how it actually works.
          </p>
        </motion.div>

        {/* Content Grid */}
        <div className="grid md:grid-cols-2 gap-6">
          {sections.map((section, index) => (
            <motion.div
              key={section.number}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
              className="bg-navy-dark/50 border border-gold/20 rounded-2xl p-6 hover:border-gold/40 transition-colors"
            >
              {/* Section Header */}
              <div className="flex items-start gap-4 mb-4">
                <div className="w-12 h-12 bg-gold/10 rounded-xl flex items-center justify-center flex-shrink-0">
                  <section.icon className="w-6 h-6 text-gold" />
                </div>
                <div>
                  <span className="text-xs text-gold/60 font-medium">#{section.number}</span>
                  <h3 className="text-xl font-semibold text-white">{section.title}</h3>
                </div>
              </div>

              {/* Content */}
              {section.content && (
                <div className="space-y-2 mb-4">
                  {section.content.map((text, i) => (
                    <p key={i} className="text-white/70 text-sm">{text}</p>
                  ))}
                </div>
              )}

              {/* Highlight Box */}
              {section.highlight && (
                <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-3 mb-4">
                  <div className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
                    <p className="text-green-300 text-sm">{section.highlight}</p>
                  </div>
                </div>
              )}

              {/* Bullets */}
              {section.bullets && (
                <div className="space-y-2 mb-4">
                  {section.bullets.map((bullet, i) => (
                    <div key={i} className="flex items-center gap-2">
                      <div className="w-1.5 h-1.5 bg-gold rounded-full" />
                      <span className="text-white/80 text-sm">{bullet}</span>
                    </div>
                  ))}
                </div>
              )}

              {/* Warning */}
              {section.warning && (
                <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-3 mb-4">
                  <div className="flex items-start gap-2">
                    <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                    <p className="text-amber-300 text-sm">{section.warning}</p>
                  </div>
                </div>
              )}

              {/* Note */}
              {section.note && (
                <div className="flex items-start gap-2 mt-3">
                  <Lightbulb className="w-4 h-4 text-gold flex-shrink-0 mt-0.5" />
                  <p className="text-white/60 text-xs">{section.note}</p>
                </div>
              )}

              {/* Distribution */}
              {section.distribution && (
                <div className="space-y-2 mt-4">
                  <p className="text-white/60 text-xs mb-2">Profit Distribution:</p>
                  {section.distribution.map((item, i) => (
                    <div key={i} className="flex items-center justify-between bg-navy/50 rounded-lg px-3 py-2">
                      <span className="text-white/70 text-sm">{item.label}</span>
                      <span className={`font-semibold ${item.color}`}>{item.percent}</span>
                    </div>
                  ))}
                </div>
              )}

              {/* Example */}
              {section.example && (
                <div className="mt-4">
                  <div className="bg-navy/50 rounded-lg p-4 mb-3">
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-white/60 text-sm">Fund Size:</span>
                      <span className="text-white font-semibold">{section.example.fund}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-white/60 text-sm">Monthly Profit:</span>
                      <span className="text-green-400 font-semibold">{section.example.profit}</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    {section.example.splits.map((split, i) => (
                      <div key={i} className="flex items-center justify-between text-sm">
                        <span className="text-white/70">{split.label}</span>
                        <span className="text-gold font-medium">{split.amount}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Formulas */}
              {section.formulas && (
                <div className="space-y-2 mb-4">
                  {section.formulas.map((formula, i) => (
                    <div key={i} className="bg-navy/50 rounded-lg px-3 py-2">
                      <code className="text-gold text-sm">{formula}</code>
                    </div>
                  ))}
                </div>
              )}

              {/* Risk Management */}
              {section.riskManagement && (
                <div className="mt-4">
                  <p className="text-white/60 text-xs mb-2">Strong AI Risk Management:</p>
                  <div className="space-y-1">
                    {section.riskManagement.map((item, i) => (
                      <div key={i} className="flex items-center gap-2">
                        <CheckCircle className="w-3 h-3 text-green-400" />
                        <span className="text-white/70 text-sm">{item}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </motion.div>
          ))}
        </div>

        {/* Summary Box */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mt-12 bg-gradient-to-r from-gold/10 via-gold/5 to-gold/10 border border-gold/30 rounded-2xl p-8"
        >
          <h3 className="text-2xl font-bold text-white mb-6 text-center">Summary</h3>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
              <p className="text-white/80 text-sm">DSJEX is a transparent, intelligent trading platform</p>
            </div>
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
              <p className="text-white/80 text-sm">Investor profits come entirely from real trading activity</p>
            </div>
            <div className="flex items-start gap-3">
              <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
              <p className="text-white/80 text-sm">Only 1% of capital is used for BTC/USDT trading</p>
            </div>
            <div className="flex items-start gap-3">
              <XCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
              <p className="text-white/80 text-sm">It is NOT gambling and NOT a Ponzi scheme</p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
